// <auto-generated />
using Krankenhausinformationssystem.Daten;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Krankenhausinformationssystem.Migrations
{
    [DbContext(typeof(KrankenhausContext))]
    partial class KrankenhausContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Krankenhausinformationssystem.Model.Behandlung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arzt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BehandlungsDatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Medikation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Behandlungen");
                });

            modelBuilder.Entity("Krankenhausinformationssystem.Model.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Geburtsdatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Geschlecht")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patienten");
                });
#pragma warning restore 612, 618
        }
    }
}
